### ISSUE TITLE
how to get 93 in baseline?

### ISSUE THREAD

**Issue by laoxihongshi** [xiaolai-sqlai/gluon-reid#5]
thx for your job!
this is my cmd:
```python train.py --num-gpus 1 --batch-size 32 --epochs 20,40,60 ```
the other setings are default.
this is my eval results:
```top1:0.367041 top5:0.561798 top10:0.655431 mAP:0.269477```
why?
pls help me!

my mistake

**Comment by luohuan2uestc** [comment]
my mistakes sry
